language: php

sudo: false

php:
    - 7.1
    - 7.2
    - 7.3
    - nightly

env:
    - SYMFONY_VERSION=4.1.* # (until 07/2019)
    - SYMFONY_VERSION=4.2.* # (until 01/2020)
    - SYMFONY_VERSION=4.3.* # (until 07/2020)
    # - SYMFONY_VERSION=4.4.* # LTS (11/2019, until 11/2023)
    - DEPENDENCIES=dev

before_install:
    - composer self-update
    - if [ "$DEPENDENCIES" == "dev" ]; then composer config minimum-stability $DEPENDENCIES; fi;
    - if [ "$SYMFONY_VERSION" != "" ]; then composer --no-update require symfony/symfony:${SYMFONY_VERSION}; fi;

install:
    - composer update
    - vendor/bin/simple-phpunit install

script:
    - composer validate --strict --no-check-lock
    - vendor/bin/simple-phpunit --coverage-text --verbose

notifications:
    email:
        - "florian.preusner@8points.de"

matrix:
    allow_failures:
        - env: DEPENDENCIES=dev
        - php: nightly
