language: php

sudo: false

php:
    - 7.0
    - 7.1
    - 7.2
    - nightly

env:
    - SYMFONY_VERSION=2.7.* # LTS (until 05/2019)
    - SYMFONY_VERSION=2.8.* # LTS (until 11/2019)
    - SYMFONY_VERSION=3.4.* # LTS (until 11/2021)
    - SYMFONY_VERSION=4.0.* # (until 01/2019)
    - SYMFONY_VERSION=4.1.* # (until 07/2019)
    # - SYMFONY_VERSION=4.2.* # (11/2018, until 01/2020)
    # - SYMFONY_VERSION=4.3.* # (05/2019, until 07/2020)
    # - SYMFONY_VERSION=4.4.* # LTS (11/2019, until 11/2023)
    - SYMFONY_VERSION=dev-master

before_install:
    - composer self-update
    - if [ "$DEPENDENCIES" == "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
    - if [ "$SYMFONY_VERSION" != "" ]; then composer --no-update require symfony/symfony:${SYMFONY_VERSION}; fi;

install: composer update

script: ./vendor/bin/phpunit --coverage-text

notifications:
    email:
        - "florian.preusner@8points.de"

matrix:
    exclude:
        - php: 7
          env: SYMFONY_VERSION=4.0.* # requires PHP ^7.1.3
        - php: 7
          env: SYMFONY_VERSION=4.1.* # requires PHP ^7.1.3
        - php: 7
          env: SYMFONY_VERSION=dev-master # requires PHP ^7.1.3
    allow_failures:
        - env: SYMFONY_VERSION=dev-master
        - php: nightly
